export const restorationShade = [
  {
    category: "restorationShade",
    label: "A1",
    value: "A1",
    color: "#DED0AD",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "A2",
    value: "A2",
    color: "#DECA98",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "A3",
    value: "A3",
    color: "#DBC289",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "A3.5",
    value: "A3.5",
    color: "#D9BA77",
  },
  {
    category: "restorationShade",
    label: "A4",
    value: "A4",
    color: "#CEAD68",
    disabled: false,
    isHide: false,
  },
 
  {
    category: "restorationShade",
    label: "B1",
    value: "B1",
    color: "#DFD2B2",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "B2",
    value: "B2",
    color: "#DCCA9A",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "B3",
    value: "B3",
    color: "#DCC381",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "B4",
    value: "B4",
    color: "#D8BB77",
    disabled: false,
    isHide: false,
  },
 
  {
    category: "restorationShade",
    label: "C1",
    value: "C1",
    color: "#D3C199",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "C2",
    value: "C2",
    color: "#CEBA85",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "C3",
    value: "C3",
    color: "#CEBA85",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "C4",
    value: "C4",
    color: "#C2A265",
    disabled: false,
    isHide: false,
  },
 
  {
    category: "restorationShade",
    label: "D2",
    value: "D2",
    color: "#D5C499",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "D3",
    value: "D3",
    color: "#D6C290",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "D4",
    value: "D4",
    color: "#D3BD81",
    disabled: false,
    isHide: false,
  },
 
  {
    category: "restorationShade",
    label: "OM1",
    value: "OM1",
    color: "#E0D8CB",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "OM2",
    value: "OM2",
    color: "#E1DAC8",
    disabled: false,
    isHide: false,
  },
  {
    category: "restorationShade",
    label: "OM3",
    value: "OM3",
    color: "#E3DCCA",
    disabled: false,
    isHide: false,
  },
//   {
//     category: "restorationShade",
//     label: "Other",
//     value: "other",
//     color: "#ffff",
//     disabled: false,
//     isHide: false,
//   },
]